version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  maven:
    image: maven:3.9.6-eclipse-temurin-21
    container_name: maven-test
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - db
    command: >
      bash -c "
        apt-get update && apt-get install -y postgresql-client &&
        echo 'Esperando DB...' &&
        until pg_isready -h db -U postgres; do sleep 1; done &&
        echo 'DB lista. Ejecutando tests...' &&
        mvn clean test
      "

  backend:
    build: .
    container_name: spring-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db
      - maven

volumes:
  postgres_data:
